### ISSUE TITLE
ended() method not firing

### ISSUE THREAD

**Issue by lukeliasi** [kaorun343/vue-youtube-embed#14]
Nothing is happening in the ended() method when the video ends.

```
<script>
export default {
  methods: {
    ended() {
      console.log('Ended');
    }
  } 
}
</script>

<youtube :video-id="videoId" @ready="ready" @ended="ended" player-width="100%" 
  player-height="57" :player-vars="{ autoplay: 0, controls: 1, modestbranding: 1, showinfo: 0, rel: 0 }">
</youtube>
```

**Comment by kaorun343** [comment]
I've checked whether the event happens by running this repository's example, but it worked well (`ended` method was fired)...... Could you tell me more detail? (browser, version, etc...)

**Comment by lukeliasi** [comment]
I've tested the example and can see it console.log when the video ends. But how do I trigger some code when the video has ended? For example the equivalent in the Angular version would be:

$scope.$on('youtube.player.ended', function ($event, player) {
    // code when video has ended
});

Could you give me an example?
Thanks.

**Comment by kaorun343** [comment]
https://github.com/kaorun343/vue-youtube-embed/blob/master/play/Events.vue

like this.

When finished playing a video, the event is going to be fired.

**Comment by lukeliasi** [comment]
Thank you very much, copied the example and working.
