### ISSUE TITLE
Unable to change video

### ISSUE THREAD

**Issue by kwnovi** [kaorun343/vue-youtube-embed#15]
Hi, thanks for the composant ! 

I don't know if it's a bug or a bad use but I can't manage to change the video on the player.
 
`  div#player 
    youtube(:video-id="current_song.id" player-width="0"  @ready="isReady"  @playing="isPlaying")
`
Vuejs data : 
`      current_song : {
          "title" : "Tierney Terrace",
          "artist" : "Loyle Carner",
          "id" : "2WQSAkYL70I",
          "new" : false,
          "isActive" : false
     }
`

And triggering a function changing the current_data object (with a new ID) doesn't update the player. Is it possible to change the  videoId of the player while the video is playing ? (meaning, stop it and start it on a new video)

**Comment by kaorun343** [comment]
If you'd like to start playing the new video automatically, please give  `:player-vars="{autoplay: 1}"` to `<youtube>` component.
If what you'd like to do is not what I explained, could you produce a live example, or code in markdown?

**Comment by kaorun343** [comment]
In addition, here is an example.

https://github.com/kaorun343/vue-youtube-embed/blob/master/play/UpdateVideoId.vue

**Comment by kwnovi** [comment]
Indeed I was missing this options, thanks you very much for the quick and detailed answer !
