### ISSUE TITLE
Grab ID from url entered into text input field

### ISSUE THREAD

**Issue by jasperf** [kaorun343/vue-youtube-embed#17]
Opened a thread on it [here](https://forum.vuejs.org/t/vue-youtube-embed-component-grab-id-from-url-entered-into-text-input-field/8219) Installed your package and trying to integrate it with my basic knowledge of things. Could you have a look see? And perhaps this can then again be used as another example file as well.

**Comment by kaorun343** [comment]
I saw that thread.
I'll close this issue.
