### ISSUE TITLE
Optionally load player only after clicking on a preview image

### ISSUE THREAD

**Issue by Sopamo** [kaorun343/vue-youtube-embed#18]
I'm using vue-youtube-embed in quite a few projects now, thanks for the great work!

I'm currently working on an application for mobile devices where I want to display multiple (10+) videos on one page, but the performance is really bad, especially on low end devices.
I'd suggest adding an option where only an image tag with the preview image is loaded at first and after the user clicks on the image the real player is loaded and plays the video.
If you want I can implement the functionality and submit a pull request.

**Comment by kaorun343** [comment]
Thanks for using this library 😄 

Your suggestion sounds nice to me.
However, writing like this is not so hard for users, I think. 

(I haven't tested this code whether it works well or not.)

```html
<template>
  <img v-if="!clicked" src="preview-image.png" @click="clicked=true">
  <youtube v-else :video-id="videoId"></youtube>
</template>

<script>
export default {
  name: 'Wrapper',
  data () {
    return {
      clicked: false
    }
  },
  props: {
    videoId: String
  }
}
</script>
```

**Comment by Sopamo** [comment]
Sure thing, but I'd need an extra component for that and as this could be a recurring problem I'd think it would fit great into this library, something like ```<youtube :preview="true"></youtube>```

**Comment by kaorun343** [comment]
OK, I see. 
I'm looking forward to receive a PR from you. 😃

**Comment by Sopamo** [comment]
I now started implementing the feature here: https://github.com/Sopamo/vue-youtube-embed/tree/add-preview-mode
The basic functionality works, I'm planning to add some tests and make the preview mode a bit more fancy :)

**Comment by kaorun343** [comment]
I'll close this because of inactivity.

**Comment by Sopamo** [comment]
Hallo,

vielen Dank für Ihre Email.

Ich bin vom 07.04. bis einschließlich 17.04. im Urlaub. 
In dringenden Fällen wenden Sie sich bitte per E-Mail an Herrn Roth: r.roth@sopamo.de

I'm on vacation between the 7th of April until 17th of April. If you need immediate assistance please contact Mr. Roth: r.roth@sopamo.de

Mit freundlichen Grüßen
Paul Mohr
