### ISSUE TITLE
how access player object in youtube component?

### ISSUE THREAD

**Issue by gn-spawn** [kaorun343/vue-youtube-embed#20]
i want to do getCurrentTime() method.
how can use it?

**Comment by kaorun343** [comment]
@gn-spawn

Hi.

Every events pass a player object.
Please check my vue-play example.

**Comment by kaorun343** [comment]
Ah, please check here.

https://github.com/kaorun343/vue-youtube-embed/blame/master/README.md#L125

**Comment by kaorun343** [comment]
Or, how about `vm.$refs.yourPlayer.player`?

https://github.com/kaorun343/vue-youtube-embed/blob/master/src/player.js#L43
