### ISSUE TITLE
Load locally

### ISSUE THREAD

**Issue by Christilut** [kaorun343/vue-youtube-embed#23]
How do you load this component locally? I'd prefer that it isn't available globally.

**Comment by kaorun343** [comment]
@Christilut 

Hi.

You can import `<youtube>` component like this below.

```js
import { YouTubePlayer } from 'vue-youtube-embed'
```

Also, since v2.1.1, you can avoid installing that component globally like this.

**Comment by Christilut** [comment]
Thanks for the response.
I tried it like that but it shows no player.

```html
                <youtube :video-id='getYoutubeId(val)'></youtube>
```

```js
import { getIdFromURL, YouTubePlayer } from 'vue-youtube-embed'

export default {
  components: {
    Youtube: YouTubePlayer
  }
}
```

**Comment by kaorun343** [comment]
Oh, I missed writing a sample code...

```js
import Vue from 'vue'
import VueYoutubeEmbed, { YouTubePlayer as Youtube } from 'vue-youtube-embed'

Vue.use(VueYoutubeEmbed, { global: false })

export default {
  components: { Youtube }
}
```

**Comment by Christilut** [comment]
Thanks

**Comment by Christilut** [comment]
So I did exactly this but I can use the `youtube` element in any component now... So it's still a global.

I haven't written a vue plugin myself but I do use many and I never need to do `Vue.use` for them, I only ever do that for the big frameworks that I want to be global. I think the initialization code of your plugin might need to be written slightly different?

**Comment by kaorun343** [comment]
It's ensured that Vue's plugin is installed only once if plugin users write `Vue.use(somePlugin)` several times.
What I wrote at this plugin's install function should be ran only once. Also, I think it makes maintaining this plugin hard to import `Vue` internally.
