### ISSUE TITLE
ready function never gets called

### ISSUE THREAD

**Issue by Fermain** [kaorun343/vue-youtube-embed#24]
Using your example, I am using an identical ready function.

However it doesn't seem to fire, even though the videos load fine.

This means I don't get local access to this.player, any advice?

**Comment by Fermain** [comment]
Hi Fermain, did you make sure you were listening to those events from the child component?

If you don't have something like @ready="ready", your ready function is obviously never going to be called.

**Comment by LeszekKicior** [comment]
I seem to have a similar problem - the 'ready' event seems to never fire, which prevents me from controlling the player.
