### ISSUE TITLE
Using with Nuxtjs (SSR)

### ISSUE THREAD

**Issue by pwnz22** [kaorun343/vue-youtube-embed#26]
I have problems with rendering player in the page. It's rendering the player one time but when i refresh the page it will not render again, just remaining a div with id `<div id="youtube-player-18"></div>` like this.

Any ideas on that?

**Comment by FranckFreiburger** [comment]
@pwnz22 meanwhile, you can try https://github.com/egoist/vue-no-ssr

**Comment by stuartcaney** [comment]
Has anyone had any luck with getting this to work? i'm using the [prerender-spa-plugin](https://www.npmjs.com/package/prerender-spa-plugin) and having the same problem. Loads one time, but not on refresh.

**Comment by kasparasg** [comment]
This has helped me out in the meantime https://nuxtjs.org/api/components-no-ssr/ ☝️
