### ISSUE TITLE
Pause on time and play again

### ISSUE THREAD

**Issue by EmilMoe** [kaorun343/vue-youtube-embed#28]
Is it possible with this plugin to do this?

1. Pause the video when it hits a time, like 5:30
1. Start the player again from a command

**Comment by kaorun343** [comment]
@EmilMoe 

Hi.

You can use `player.getCurrentTime`, so how about calling the method frequently by using `setInterval` function to check the current time ? Then pause the video, please.

**Comment by EmilMoe** [comment]
So I assume pause and playing is no problem? :-) 

Yeah that could work, calling it every 5 second. It's not possible to somehow register, in your component, to count every second while a video is playing and by that expose every second? Just an idea.

Thanks for the product. Sorry, I'm currently on the look for a component, so I haven't tested, just need to know if it meets our needs first.

**Comment by kaorun343** [comment]
```js
export default {
  methods: {
    playerReady(player) {
      this.timerId = setTimeInterval(() => {
        if (player.getCurrentTime > 60) {
          player.pause()
          clearInterval(this.timerId)
        }
      })
    }
  }
}
```
