### ISSUE TITLE
how to add parameters (showinfo=0) in iframe url

### ISSUE THREAD

**Issue by eelbahri** [kaorun343/vue-youtube-embed#36]
Hello, 

I'd like to add "&showinfo=0" in the url because I don't want share buttons and title, is there a attribute which can help me ? 

Thanks !

**Comment by eelbahri** [comment]
I did this : 
`:video-id='videoid+"?showinfo=0&"'`

**Comment by vieko** [comment]
this worked for me `:player-vars="{ rel: 0, showinfo: 0, autoplay: 0 }"`
