### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by haog1** [kaorun343/vue-youtube-embed#38]
Since I changed HTTP to HTTPS then i found this error. 

```
www-widgetapi.js:117 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://centralhub.glorycitychurch.com').
g.C @ www-widgetapi.js:117
```

I am guessing that it is probably by the `<youtube>`, which uses http request as default. So where can I change it?

**Comment by krishaamer** [comment]
Same problem here. Any fixes so far?

**Comment by waspar** [comment]
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://my-site.ru').

AND ONLY IN GOOGLE CHROME!

**Comment by michelmany** [comment]
Same error here: **Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ...**

Even after updating this component to the last version: 2.1.3

Any idea on that? 

Thanks!

**Comment by kaorun343** [comment]
Could you try this?
https://stackoverflow.com/questions/16050024/youtube-iframe-api-fails-to-post-message

**Comment by Neharsputhran** [comment]
I am also facing the same problem  www-widgetapi.js:1257  Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://netflix-clone-eight-lilac.vercel.app') 

Any solutions
