### ISSUE TITLE
Compiled and minified file

### ISSUE THREAD

**Issue by AStaroverov** [kaorun343/vue-youtube-embed#4]
if it is not possible to use some bundler with require or import.

**Comment by kaorun343** [comment]
I suppose this package should be used with Webpack or Browserify, so I thought it's not needed to commit compiled or minified file into this repository. Of course, in the npm package, the compiled file is included.

**Comment by AStaroverov** [comment]
Thx for answer, but npm have compiled file are not obvious.
It may be necessary to add a hint for this?

ср, 23 марта 2016 г., 14:12 Kaorun343 <notifications@github.com>:

**Comment by kaorun343** [comment]
That's right. I'll fix README.md. Thanks.
