### ISSUE TITLE
Get event argument from @ready

### ISSUE THREAD

**Issue by Craft4u** [kaorun343/vue-youtube-embed#42]
Maybe be good to pass an event (not event.target) to this function : 
OLD --- onReady: function (event) {
            this$1.setMute(this$1.mute);
            this$1.$emit('ready', event.target);
          }

NEW ---  onReady: function (event) {
            this$1.setMute(this$1.mute);
            this$1.$emit('ready', event);
          }

Because in something situation i am going to use event.data and can't get it.

**Comment by kaorun343** [comment]
I've just fixed this.
