### ISSUE TITLE
Ability to set start time for the video?

### ISSUE THREAD

**Issue by mattias-persson** [kaorun343/vue-youtube-embed#55]
Is it possible to set a start time for a video? Similare to sharing with the `?t=` parameter appended to the Video ID.

**Comment by mattias-persson** [comment]
Nevermind, `:player-vars="{start: 5}"` 🙂

**Comment by monumehta** [comment]
start time does not change when I am changing it form mounted function 

mounted(){
this.playerVars.start = Math.floor(data[0].skip)
this.videoId = data[0].video_id
}

**Comment by mattias-persson** [comment]
You probably need to re-render the youtube-component. Give it a `:key=""` and include the start time in that key, then it should re-render every time the start time changes.
