### ISSUE TITLE
How pausePlayer() with custom btn?

### ISSUE THREAD

**Issue by hardusik** [kaorun343/vue-youtube-embed#77]
How I can pausePlayer() with custom btn?

**Comment by jonalxh** [comment]
Readme shows how to do it with pauseVideo(), but you hace to instantiate the player in a variable, take a look at https://github.com/kaorun343/vue-youtube-embed#example-code

**Comment by hardusik** [comment]
> https://github.com/kaorun343/vue-youtube-embed#example-code

it's not clear for me.
my main.js contain:
```javascript
import VueYouTubeEmbed from 'vue-youtube-embed'; 
Vue.use(VueYouTubeEmbed);
```

in component.vue
```javascript
<youtube :id="item.link" :video-id="item.link" player-width="100%" player-height="325px"></youtube>
```
i use ```v-for```, because i have several video items

as i understand, i need to add ```@playing ``` event listener on ```<youtube />```
but i cant understand how works ```pause()``` method, can you help with it?

**Comment by jonalxh** [comment]
Yeah, add playing event to your component instance and after that, assign the value to a variable:

```
<youtube :id="item.link" :video-id="item.link" player-width="100%" player-height="325px" @playing="createVideoElement"></youtube>

<button @click="pause()">Pause</button>
```

Then, In your JS do someting like this:

```
data() {
	return { 
                videoElem: ""
        }
},
methods: {
      getVideoElem(event) {
                this.videoElem = event
       },
       pause() {
                this.videoElem.pauseVideo()
       }
}
```

First you need a variable to save the video instance, having it you just need to apply the pauseVideo().
