### ISSUE TITLE
Support both 2.0 and 1.x

### ISSUE THREAD

**Issue by kaorun343** [kaorun343/vue-youtube-embed#8]
Supporting only Vue.js 2.0 / Vue.js 1.x is easy, but I'd like to support both.
Do you have any idea...?

**Comment by chocochaii** [comment]
If I understand correctly, it's now supporting only 1.x, right? (correct me if I'm wrong)
I believe that it would be great if it will support both.
It will still be advantage to 1.x developers. Anyway, Vue 2.0 became the current version and I think, in the near future, most of developers will turn to use 2.0, and if you make this component supported, it will be one useful component, I can tell!

I'm working on Vue 2.0 as well and hopefully I will include your component to my project for sure :)

**Comment by kaorun343** [comment]
I decided to support only 2.x.

**Comment by rigor789** [comment]
I went ahead and update it to be compatible with 2.x #10
