### ISSUE TITLE
IE 11 - cuevideobyid is not a function

### ISSUE THREAD

**Issue by livioalves** [kaorun343/vue-youtube-embed#9]
When I try to play the next video on IE11, it throws cuevideobyid is not a function.

**Comment by kaorun343** [comment]
I don't have IE11 environment..., so could you try this?
It seems changing `videoId` before `ready` hook will cause that error.

1. remove `videoId: 'update'` inside `WatchOptions`
2. add `this.$watch('videoId', 'update')` after `this.$emit('ready', event.target)`

**Comment by livioalves** [comment]
I changed it, worked on Chrome but not on IE.

**Comment by kaorun343** [comment]
Could you reproduce your code?
I ran the example on IE11, but it worked well(but i needed to use babel)
